services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    restart: always

  weather_pipeline:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: weather_etl_pipeline
    restart: always
    ports:
    - "8080:8080"
    - "8501:8501"
    depends_on:
      - ollama
    environment:
    - OLLAMA_HOST=0.0.0.0
    - OLLAMA_BASE_URL=http://ollama:11434
    - AIRFLOW_HOME=/app/airflow_app
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__DAGS_FOLDER=/app/dags
    - AIRFLOW_ADMIN_USER=admin
    - AIRFLOW_ADMIN_PASSWORD=admin
    - PROJECT_DIR=/app
    - RAW_DIR=/app/data/raw
    - NORMALS_DIR=/app/data/raw/normals
    - DAILY_DIR=/app/data/raw/daily
    - DEBUG_DIR=/app/data/raw/debug
    - DB_PATH=/app/data/weather.duckdb
    - DBT_DIR=/app/weather_dbt
    - PYTHONUNBUFFERED=1
    - PYTHONPATH=/app
    volumes:
      - ../data:/app/data
      - ../airflow_app/logs:/app/airflow_app/logs

volumes:
  ollama_storage:
